// GET ALL PRODUCTS
export const GET_PRODUCTS_LIST = 'GET_PRODUCT_LIST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCTS_LIST_ERROR = 'PRODUCT_LIST_ERROR'

// GET A SINGLE PRODUCT BY ID
export const GET_PRODUCT_ID = 'GET_PRODUCT_ID'
export const PRODUCTS_ID_SUCCESS = 'PRODUCT_ID_SUCCESS'
export const PRODUCTS_ID_ERROR = 'PRODUCT_ID_ERROR'

// ADD TO CART

export const ADD_TO_CART = 'ADD_TO_CART'

// LOGIN USER

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
