import img1 from './Assets/img/1.jpg'
import img2 from './Assets/img/2.jpg'
import img3 from './Assets/img/3.jpg'
import img4 from './Assets/img/4.jpg'
import img5 from './Assets/img/5.jpg'
import img6 from './Assets/img/6.jpg'
import img7 from './Assets/img/7.jpg'
import img8 from './Assets/img/8.jpg'
import img9 from './Assets/img/9.jpg'
import img10 from './Assets/img/10.jpg'

const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: img1,
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: img2,
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: img3,
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: img4,
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: img5,
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: img6,
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: img7,
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: img8,
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: img9,
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: img10,
      price: 139,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
}
export default data
